name: Jennifer Schumacher
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.2561
title: 'video . digital . mobile . social '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#6f6e83'
    - '#010000'
    - '#292837'
    - '#a8a8b5'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
