name: Jennifer Schumacher
favicon: null
layout_spectrum: 0.50938
typography_spectrum: 0.8574719212483615
title: 'video . digital . mobile . social '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f6e83'
    - '#d3d3d3'
    - '#1b95e0'
    - '#424242'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
