name: JenniferSchumacher
favicon: null
layout_spectrum: 0.50938
typography_spectrum: 0.8574719212483615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.676728683989495
  saturation: 0.9928402001969516
  rhythmicContrast: 0
purpose: []
